name: Redis Update Everyday

on:
  schedule:
    - cron: "30 0 * * *" # 每天 UTC 时间 00:30 运行
  workflow_dispatch: # 允许手动触发
  repository_dispatch:
    types:
      - GetDataBase

env:
  PYTHON_VERSION: "3.12"

jobs:
  Crawler:
    name: Crawler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GIT_TOKEN }}
          persist-credentials: true # 保持认证信息

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Run Crawlers for all locales
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: |
          locales=("zh-CN" "en-US")
          for locale in "${locales[@]}"; do
            echo "Running crawler for $locale"
            python ./ALL.py "$locale"
            
            # 提交每个语言的结果
            git add .
            git commit -m "GitHub Actions Crawler $locale at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit for $locale"
          done

      - name: Generate README
        run: python ./make_readme.py

      - name: Commit README
        run: |
          git add .
          git commit -m "GitHub Actions UPDATE README at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to README"

      - name: Push changes
        run: git push
